# Generated by Django 4.2.17 on 2025-01-10 22:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default_avatar', max_length=255, verbose_name='image'),
        ),
    ]
